repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff check --config .ruff.toml
      language: system
      types: [python]

    - id: flake8
      name: flake8
      entry: flake8 --config=.flake8
      language: system
      types: [python]

    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]

    - id: coverage
      name: coverage
      entry: bash -c 'coverage run --omit=smsaero/command_line.py -m pytest && coverage report'
      language: system
      types: [python]
