language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"

before_install:
    - export PIP_USE_MIRRORS=true
install:
    - pip install -e .
    - pip install -r tests/requirements.txt
script:
    - make test
    - make coverage

branches:
    only:
        - master
